#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH		WINDOW_WIDTH_SM
#define	WINDOW_HEIGHT		WINDOW_HEIGHT_SM

#define WINDOW_WIDTH_SM		640
#define WINDOW_HEIGHT_SM	480

#define WINDOW_GAME_TITLE	"Asteroids Arcade OpenGL"

#define WINDOW_UNIT			1

#endif	// CONSTANTS_H