#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH		WINDOW_WIDTH_LG
#define	WINDOW_HEIGHT		WINDOW_HEIGHT_LG

#define WINDOW_WIDTH_LG		1920
#define WINDOW_HEIGHT_LG	1080

#define WINDOW_WIDTH_MM		1280
#define WINDOW_HEIGHT_MM	720

#define WINDOW_WIDTH_SM		720
#define WINDOW_HEIGHT_SM	480

#define WINDOW_GAME_TITLE	"Asteroids Arcade OpenGL v Vulkan"

#define WINDOW_UNIT			1

#define IMPL_VULKAN

#define NUM_ASTEROIDS		75

#define MESH_INSTANCING_ON  true

#endif	// CONSTANTS_H